import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./providers";
import { Toaster } from "sonner";
import InactivityProvider from "@/components/InactivityProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Instroom | Simplify your influencer marketing workflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${manrope.variable} antialiased`}
        suppressHydrationWarning
      >
        <AuthProvider>
          <InactivityProvider>
            {children}
          </InactivityProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}